GET localhost:3000/login/github

###

GET localhost:3000/me
cookie: accessCookie=<paste access cookie>; refreshCookie=<paste refresh cookie>

###

GET localhost:3000/refresh
cookie: accessCookie=<paste access cookie>; refreshCookie=<paste refresh cookie>
